# Generated by Django 5.1.2 on 2024-10-18 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("noteapp", "0003_remove_note_image_remove_note_pdf_image_pdf"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="folder",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notes",
                to="noteapp.folder",
            ),
        ),
        migrations.AlterField(
            model_name="note",
            name="nDate",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="note",
            name="nDescription",
            field=models.TextField(blank=True, null=True),
        ),
    ]
