# Generated by Django 5.1.2 on 2024-10-19 01:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("noteapp", "0004_alter_note_folder_alter_note_ndate_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pdf",
            name="note",
        ),
        migrations.AddField(
            model_name="note",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
        migrations.AddField(
            model_name="note",
            name="pdf",
            field=models.FileField(blank=True, null=True, upload_to="pdfs/"),
        ),
        migrations.DeleteModel(
            name="Image",
        ),
        migrations.DeleteModel(
            name="PDF",
        ),
    ]
